AzureStorageOperations/Controllers/BlobOperationsController.cs
using AzureStorageOperations.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;

namespace AzureStorageOperations.Controllers
{
    public class BlobOperationsController : Controller
    {
        static string StorageAccountName = "tcoblobuat";
        static string StorageAccountKey = "ZbdL+JZKXLUFm3VX8lR4MVA/UhR0M9z2GJElVBsxSNLMAt4nvBBwqKsurzoB9Ij6nL5zULpUsxH61OVZfeXXHQ==";
        static string ContainerName = "telematics-ecrb";
       
        // GET: BlobOperations
        public async Task<ActionResult> BlobOperaionsView()
        {
            
            FileUpload fileobj = new FileUpload();
            fileobj = await ListContainersAsyncREST(StorageAccountName, StorageAccountKey, CancellationToken.None);
            return View(fileobj);
        }


        public async Task DownloadBlob(string fileName)
        {

            string sContetType = string.Empty;
            string sContentLength = string.Empty;

            MemoryStream memStream = new MemoryStream();           

            String uri = string.Format("http://{0}.blob.core.windows.net/{1}/{2}", StorageAccountName, ContainerName,fileName);

            // Set this to whatever payload you desire. Ours is null because 
            //   we're not passing anything in.
            Byte[] requestPayload = null;

            //Instantiate the request message with a null payload.
            using (var httpRequestMessage = new HttpRequestMessage(HttpMethod.Get, uri)
            { Content = (requestPayload == null) ? null : new ByteArrayContent(requestPayload) })
            {

                // Add the request headers for x-ms-date and x-ms-version.
                DateTime now = DateTime.UtcNow;
                httpRequestMessage.Headers.Add("x-ms-date", now.ToString("R", CultureInfo.InvariantCulture));
                httpRequestMessage.Headers.Add("x-ms-version", "2017-04-17");
                

                // Add the authorization header.
                httpRequestMessage.Headers.Authorization = AzureStorageAuthenticatorHelper.GetAuthorizationHeader(
                   StorageAccountName, StorageAccountKey, now, httpRequestMessage);
                

                // Send the request.
                using (HttpResponseMessage httpResponseMessage = await new HttpClient().SendAsync(httpRequestMessage, CancellationToken.None))
                {
                    // If successful (status code = 200), 
                    //   parse the XML response for the container names.
                    if (httpResponseMessage.StatusCode == HttpStatusCode.OK)
                    {
                        String xmlString = await httpResponseMessage.Content.ReadAsStringAsync();
                        var mstream = await httpResponseMessage.Content.ReadAsStreamAsync();
                        mstream.CopyTo(memStream);
                        sContetType = httpResponseMessage.Content.Headers.ContentType.MediaType;                        
                        sContentLength =  httpResponseMessage.Content.Headers.ContentLength.ToString();                        
                    }
                }
            }

            Response.ContentType = sContetType;
            Response.AddHeader("Content-Disposition", "Attachment;filename=" + fileName);
            Response.AddHeader("Content-Length", sContentLength);
            Response.BinaryWrite(memStream.ToArray());            
        }

      
        private  async Task<FileUpload> ListContainersAsyncREST(string storageAccountName, string storageAccountKey, CancellationToken cancellationToken)
        {

            FileUpload fileobj = new FileUpload();
            List<FileUpload> filelist = new List<FileUpload>();
            // Construct the URI. This will look like this:
            //   https://myaccount.blob.core.windows.net/resource
            String uri = string.Format("http://{0}.blob.core.windows.net/{1}?restype=container&comp=list", storageAccountName, ContainerName);

            // Set this to whatever payload you desire. Ours is null because 
            //   we're not passing anything in.
            Byte[] requestPayload = null;

            //Instantiate the request message with a null payload.
            using (var httpRequestMessage = new HttpRequestMessage(HttpMethod.Get, uri)
            { Content = (requestPayload == null) ? null : new ByteArrayContent(requestPayload) })
            {

                // Add the request headers for x-ms-date and x-ms-version.
                DateTime now = DateTime.UtcNow;
                httpRequestMessage.Headers.Add("x-ms-date", now.ToString("R", CultureInfo.InvariantCulture));
                httpRequestMessage.Headers.Add("x-ms-version", "2017-04-17");
                // If you need any additional headers, add them here before creating
                //   the authorization header. 

                // Add the authorization header.
                httpRequestMessage.Headers.Authorization = AzureStorageAuthenticatorHelper.GetAuthorizationHeader(
                   storageAccountName, storageAccountKey, now, httpRequestMessage);

                // Send the request.
                using (HttpResponseMessage httpResponseMessage = await new HttpClient().SendAsync(httpRequestMessage, cancellationToken))
                {
                    // If successful (status code = 200), 
                    //   parse the XML response for the container names.
                    if (httpResponseMessage.StatusCode == HttpStatusCode.OK)
                    {
                        String xmlString = await httpResponseMessage.Content.ReadAsStringAsync();
                        //var stream = await httpResponseMessage.Content.ReadAsStreamAsync();



                        XElement x = XElement.Parse(xmlString);
                        //foreach (XElement container in x.Element("Containers").Elements("Container"))
                        //{
                        //    Console.WriteLine("Container name = {0}", container.Element("Name").Value);
                        //}
                        foreach (XElement container in x.Element("Blobs").Elements("Blob"))
                        {
                            FileUpload obj = new FileUpload();
                            obj.FileName = container.Element("Name").Value;
                            filelist.Add(obj);
                            //Console.WriteLine("Blob name = {0}", container.Element("Name").Value);
                        }
                    }
                }
            }
            fileobj.FileUploadList = filelist;
            return fileobj;
        }


    }
}

AzureStorageOperations/Views/BlobOperations/BlobOperaionsView.cshtml
@model AzureStorageOperations.Models.FileUpload

@*<script src="~/Scripts/jquery-1.9.1.min.js"></script>*@
@*<script src="~/Scripts/jquery-1.10.2.js"></script>*@
<style>
    tr td:last-child {
        width: 1%;
        white-space: nowrap;
    }
</style>

<script type="text/javascript">

    @*$(document).ready(function () {
        if('@ViewBag.Message' == 'File Uploaded Successfully')
        {
            alert('File Uploaded Successfully dfgdfbh dbfgjhsd'bfg dsrfgbdjfhg dsnfghjbdgbf');
        }

        if ('@ViewBag.Message' == 'File is already exists') {
            alert('File is already exists');
        }

        $('#uloadTable td #openID').live('click', function () {
            var filename = $(this).parent().parent().parent().attr('id');
            $(this).parent().parent().parent().remove();
            alert("hello");
            $.ajax({
                type: "post",
                url: "/Home/RemoveUploadFile?fileName=" + filename,
                datatype: "json",
                traditional: true,
                success: function (data) {
                    alert('File Deleted');
                    if (data == 0) {
                        $('#uloadTable').remove();
                    }
                }
            });
        });
    });*@

    function Validate(e) {
        if ($("#fileuploaderID").val() != "" && $("#fileuploaderID").val() != null) {
            //return true;
        }
        else {
            alert("Please select any file to upload....")
            return false;
        }
    }
</script>

@{
    ViewBag.Title = "FileUpload";
}
<h2>Manage Blobs</h2>

@using (@Html.BeginForm("Index", "BlobOperations", FormMethod.Post, new { @id = "form1", @enctype = "multipart/form-data" }))
{
    <table>
        <tr>
            <td>
                <input type="file" name="file_Uploader" id="fileuploaderID" />
            </td>
            <td style="width:15%">
                <input type="submit" id="bttn_Upload" value="Upload" onclick="return Validate();" />
            </td>
        </tr>
    </table>

    if (Model.FileUploadList != null)
    {
        <div class="upload">
            <div style="width: 500px;">
                <table id="uloadTable" border="1">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Action</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model.FileUploadList)
                        {

                            <tr id="@item.FileName">

                                <td>@item.FileName</td>

                                <td>
                                    <a href="@Url.Action("DownloadBlob", "BlobOperations", new { @fileName = item.FileName })">
                                        <input type="button" value="Download" id="openID" />
                                        @*<img width="16" height="16" border="0" src="~/Images/view.png" class="viewc">*@
                                    </a>

                                    <a href="@Url.Action("RemoveUploadFile", "Home", new { @fileName = item.FileName })">
                                        <input type="button" value="Delete" id="RemoveID" />
                                        @*<img width="16" height="16" border="0" src="~/Images/Delete.png" class="link">*@
                                    </a>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    }
}